1-dz
Papai145/NodeJs pull request #1
Opened 2024-12-03 15:55 UTC by Papai145

2024-12-16 16:42 UTC, alex13slem requested changes

2024-12-16 16:42 UTC, alex13slem commented on 3-calc/index.js
> +      result = add(firstName, secondName);
Откуда тут Name? Это же число, а конкретно здесь - операнд

2024-12-16 16:42 UTC, alex13slem commented on 3-calc/index.js
> +      result = "произошла ошибка";
Какая ошибка? Нужно писать немного конкретнее.

2024-12-16 16:42 UTC, alex13slem commented on 4-timer/index.js
> +      timeObject["hour"] = Number(elem.slice(0, -1));
вместо ` Number(elem.slice(0, -1));` можно использовать `parseInt(elem)`

2024-12-16 16:42 UTC, alex13slem commented on 4-timer/index.js
> +const a = transformTimeArr(timeArr);
Подумайте над названиями переменных и функций, если функция во что-то трансформирует, то должно быть понятно во что, или должно быть понятно что она возвращает, например getTimeData

2024-12-21 12:07 UTC, Papai145 commented on 3-calc/index.js
> +      result = add(firstName, secondName);
let result;
  switch (sign) {
    case "add":
      result = add(num1, num2);

2024-12-21 12:08 UTC, Papai145 commented on 3-calc/index.js
> +      result = "произошла ошибка";
result = `произошла ошибка операции, введите:
      <node index.js [операнд1] [операнд2] [add|multiply]>`;

2024-12-21 12:08 UTC, Papai145 commented on 4-timer/index.js
> +      timeObject["hour"] = Number(elem.slice(0, -1));
исправил, согласен так проще

2024-12-26 09:57 UTC, alex13slem approved these changes

2024-12-26 17:11 UTC, merged